on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: actions/checkout@v5
      - run: echo "${{SECRETS.GITHUB_TOKEN}}" | podman login -u "${{github.actor}}" --password-stdin ghcr.io
      - run: podman build -t ghcr.io/charles4090/trisquel-container:latest .
      - run: podman push ghcr.io/charles4090/trisquel-container:latest
        if: github.event_name != "pull_request"
