on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        suite:
          - aramo
          - ecne
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{SECRETS.GITHUB_TOKEN}}" | podman login -u "${{github.actor}}" --password-stdin ghcr.io
      - run: podman build --build-arg=suite="${{matrix.suite}}" -t "ghcr.io/charles25565/trisquel-container:${{matrix.suite}}" .
      - name: Ensure the container has working `cat` and correct suite
        run: podman run "ghcr.io/charles25565/trisquel-container:${{matrix.suite}}" cat /etc/os-release | grep -q "${{matrix.suite}}"
      - run: podman push "ghcr.io/charles25565/trisquel-container:${{matrix.suite}}"
        if: github.event_name != 'pull_request'
